Repository weaveworks/pctl, pull requests merged in 2021-08, with the labels that each got.

#248 Refactor `search`, `list`, and `show` into `get`
  README.md
  cmd/pctl/get.go
  cmd/pctl/list.go
  cmd/pctl/main.go
  cmd/pctl/search.go
  cmd/pctl/show.go
  pkg/catalog/fakes/fake_catalog_manager.go
  pkg/catalog/list.go
  pkg/catalog/list_test.go
  pkg/catalog/manager.go
  tests/integration/integration_docgen_test.go
  tests/integration/integration_get_test.go
  tests/integration/integration_list_test.go
  tests/integration/integration_search_test.go
  tests/integration/integration_show_test.go
Labels: kind/docs, kind/improvement, kind/ux

#244 Add support for bootstraping repo with pctl config
  cmd/pctl/add.go
  cmd/pctl/bootstrap.go
  cmd/pctl/main.go
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_suite_test.go
  pkg/bootstrap/bootstrap_test.go
  pkg/bootstrap/export_test.go
  tests/integration/e2e_test.go
  tests/integration/integration_bootstrap_test.go
  tests/integration/integration_docgen_test.go
Labels: kind/feature

#255 fix typo in bootstrap test
  tests/integration/integration_bootstrap_test.go
Labels: skip-release-notes

#253 Rename `prepare` to `install`
  cmd/pctl/install.go
  cmd/pctl/main.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  tests/integration/install_test_cluster.go
  tests/integration/integration_docgen_test.go
  tests/integration/integration_install_test.go
  tests/integration/integration_suite_test.go
Labels: kind/improvement

#259 add 0.3.0 release notes
  docs/release_notes/v0.3.0.md
  pkg/version/release.go
Labels: skip-release-notes

#261 Add slack bot for release notification on profiles channel
  .github/workflows/release.yaml
Labels: kind/feature

#262 Add commit message option for when pushing to a remote repo
  cmd/pctl/add.go
  cmd/pctl/upgrade.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/upgrade/upgrade.go
Labels: kind/feature

#264 Added release doc
  docs/release_notes/v0.4.0.md
  pkg/version/release.go
Labels: skip-release-notes

#266 Using a proper slack notification action
  .github/workflows/release.yaml
Labels: skip-release-notes

#265 Rename `--profile-url` to `--profile-repo-url`
  README.md
  cmd/pctl/add.go
  tests/integration/integration_add_test.go
Labels: kind/improvement, kind/ux

#267 add tagging to release process
  .github/workflows/release.yaml
  README.md
Labels: skip-release-notes

#268 add 0.5.0 release notes
  docs/release_notes/v0.5.0.md
  pkg/version/release.go
Labels: skip-release-notes

#263 Refactor integration tests
  tests/integration/e2e_test.go
  tests/integration/integration_add_test.go
  tests/integration/integration_bootstrap_test.go
  tests/integration/integration_docgen_test.go
  tests/integration/integration_get_test.go
  tests/integration/integration_suite_test.go
  tests/integration/integration_update_test.go
  tests/integration/integration_version_test.go
Labels: skip-release-notes

#269 Use GITHUB_TOKEN rather than GIT_TOKEN
  pkg/git/scm_git.go
  pkg/git/scm_test.go
  tests/integration/integration_add_test.go
Labels: kind/improvement

#275 support cloud provider authentication and setting KUBECONFIG
  cmd/pctl/main.go
  go.sum
  pkg/client/client.go
Labels: kind/bug

#276 escape multilines when passing release notes in workflow
  .github/workflows/release.yaml
Labels: skip-release-notes

#278 add v0.6.0 release notes
  docs/release_notes/v0.6.0.md
  pkg/version/release.go
Labels: skip-release-notes

#284 bump deps
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#272 Add tickmarks and flux-like output to pctl output
  README.md
  cmd/pctl/add.go
  cmd/pctl/bootstrap.go
  cmd/pctl/get.go
  cmd/pctl/main.go
  cmd/pctl/upgrade.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/cluster/waiter.go
  pkg/git/git.go
  pkg/git/scm_git.go
  pkg/install/artifact/artifact.go
  pkg/log/log.go
  pkg/log/log_suite_test.go
  pkg/log/log_test.go
  pkg/upgrade/upgrade.go
  tests/integration/e2e_test.go
  tests/integration/integration_add_test.go
  tests/integration/integration_bootstrap_test.go
  tests/integration/integration_get_test.go
  tests/integration/integration_update_test.go
Labels: kind/improvement, kind/ux

#290 Remove extra new lines from output
  cmd/pctl/add.go
Labels: skip-release-notes

#288 only add the installation directory when creating a PR
  cmd/pctl/add.go
  cmd/pctl/upgrade.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/git/fakes/fake_git.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/upgrade/repo/manager.go
  pkg/upgrade/repo/manager_test.go
Labels: kind/improvement

#289 Change installation directory to default to profile installation name
  cmd/pctl/add.go
  tests/integration/e2e_test.go
  tests/integration/integration_add_test.go
  tests/integration/integration_update_test.go
Labels: kind/feature

#271 Shorten generated resources names
  pkg/install/artifact/artifact.go
  pkg/install/artifact/artifact_chart_test.go
  pkg/install/artifact/artifact_kustomize_test.go
  pkg/install/artifact/artifact_nested_test.go
  tests/integration/e2e_test.go
  tests/integration/integration_add_test.go
Labels: kind/improvement

#291 Add 0.7.0 notes
  docs/release_notes/v0.7.0.md
  pkg/version/release.go
Labels: skip-release-notes
