Repository weaveworks/pctl, pull requests merged in 2021-04, with the labels that each got.

#7 Add help to Makefile
  Makefile
Labels: skip-release-notes

#6 Add license
  LICENSE
Labels: skip-release-notes

#10 Fixing linting and adding a more strict linter
  .golangci.yml
  Makefile
  cmd/pctl/main.go
  pkg/catalog/catalog.go
  pkg/catalog/search.go
Labels: kind/feature

#8 Add show command
  .github/workflows/test.yaml
  .gitignore
  Makefile
  README.md
  cmd/pctl/main.go
  go.mod
  go.sum
  pkg/catalog/catalog.go
  pkg/catalog/search.go
  pkg/catalog/search_test.go
  pkg/catalog/show.go
  pkg/catalog/show_test.go
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#13 Show a sensible message in the CLI heading
  cmd/pctl/main.go
Labels: skip-release-notes

#18 Create a profile subscription to be installed into a cluster
  README.md
  cmd/pctl/main.go
  go.mod
  go.sum
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/writer/writer.go
  pkg/writer/writer_suite_test.go
  pkg/writer/writer_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#27 Modify the actions to only run integration test on push to main
  .github/workflows/integration_test.yaml
  .github/workflows/unit_test.yaml
Labels: kind/improvement, skip-release-notes

#28 Fix the assignment to the environment property
  .github/workflows/integration_test.yaml
Labels: bug, skip-release-notes

#24 Add opening a PR for a repository in which the profile subscription file is generated
  cmd/pctl/main.go
  go.mod
  go.sum
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/git/fakes/fake_git.go
  pkg/git/fakes/fake_runner.go
  pkg/git/fakes/fake_scm.go
  pkg/git/git.go
  pkg/git/git_suite_test.go
  pkg/git/git_test.go
  pkg/git/runner.go
  pkg/git/runner_test.go
  pkg/git/scm_git.go
  pkg/git/scm_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#35 Add kind/improvement to valid pr labels list
  .github/workflows/pr-labels.yaml
Labels: skip-release-notes

#34 Add --output flag to search and show commands
  .github/workflows/integration_test.yaml
  .github/workflows/unit_test.yaml
  Makefile
  README.md
  cmd/pctl/main.go
  go.mod
  go.sum
  pkg/formatter/formatter.go
  pkg/formatter/formatter_suite_test.go
  pkg/formatter/json.go
  pkg/formatter/json_test.go
  pkg/formatter/table.go
  pkg/formatter/table_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#40 Update readme when 'make test'
  Makefile
Labels: build-and-release, skip-release-notes
