Repository weaveworks/pctl, pull requests merged in 2021-09, with the labels that each got.

#304 Fix pctl get error messages
  cmd/pctl/get.go
Labels: skip-release-notes, kind/bug

#305 add 0.8.0 release notes
  docs/release_notes/v0.8.0.md
  pkg/version/release.go
Labels: skip-release-notes

#313 Add permanent out folder setting into the config
  README.md
  cmd/pctl/add.go
  cmd/pctl/add_test.go
  cmd/pctl/bootstrap.go
  cmd/pctl/cmd_suite_test.go
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_test.go
  tests/integration/e2e_test.go
  tests/integration/integration_bootstrap_test.go
Labels: kind/feature

#315 Add upgrading to the latest version
  README.md
  cmd/pctl/upgrade.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  tests/integration/integration_upgrade_test.go
Labels: kind/feature

#317 add 0.9.0 release notes
  docs/release_notes/v0.9.0.md
  pkg/version/release.go
Labels: skip-release-notes

#319 error when user tries to upgrade a non-catalog installation
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: kind/bug

#321 Set default helm release interval to 5m
  pkg/install/artifact/artifact.go
  pkg/install/artifact/artifact_chart_test.go
Labels: kind/improvement

#322 add 0.10.0 release notes
  README.md
  docs/release_notes/v0.10.0.md
  pkg/version/release.go
Labels: skip-release-notes

#329 Update command line parsing error
  cmd/pctl/main.go
  tests/integration/integration_add_test.go
Labels: kind/bug

#332 Specify the configmap in kustomize file when creating helmchart artifact with default values
  cmd/pctl/add.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/install/artifact/artifact.go
  pkg/install/artifact/artifact_chart_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  tests/integration/e2e_test.go
  tests/integration/integration_add_test.go
Labels: kind/bug

#333 add 0.11.0 release notes
  docs/release_notes/v0.11.0.md
  pkg/version/release.go
Labels: skip-release-notes
