Repository weaveworks/pctl, pull requests merged in 2021-05, with the labels that each got.

#36 Add prepare command to prepare an environment to run profiles by installing all necessary components.
  Makefile
  README.md
  cmd/pctl/main.go
  cmd/pctl/prepare.go
  pkg/cluster/cluster_suite_test.go
  pkg/cluster/prepare.go
  pkg/cluster/prepare_test.go
  pkg/cluster/testdata/prepare.yaml
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/runner/fakes/fake_runner.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
  tests/integration/prepare_test_cluster.go
Labels: kind/feature

#30 Add support for listing and getting installed profiles
  .gitignore
  README.md
  cmd/pctl/get.go
  cmd/pctl/install.go
  cmd/pctl/list.go
  cmd/pctl/main.go
  cmd/pctl/search.go
  cmd/pctl/show.go
  go.mod
  go.sum
  pkg/subscription/get.go
  pkg/subscription/get_test.go
  pkg/subscription/list.go
  pkg/subscription/list_test.go
  pkg/subscription/manager.go
  pkg/subscription/subscription_suite_test.go
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#51 Prevent timestamp output from errors
  cmd/pctl/main.go
Labels: kind/improvement

#50 Adding prepare flux checking
  README.md
  cmd/pctl/get.go
  cmd/pctl/prepare.go
  go.mod
  go.sum
  pkg/cluster/prepare.go
  pkg/cluster/prepare_test.go
  tests/integration/prepare_test_cluster.go
Labels: kind/feature

#49 Wait for resources to be ready
  cmd/pctl/prepare.go
  go.mod
  go.sum
  pkg/cluster/fakes/fake_waiter.go
  pkg/cluster/prepare.go
  pkg/cluster/prepare_test.go
  pkg/cluster/waiter.go
  pkg/cluster/waiter_test.go
Labels: kind/improvement

#54 pctl install generates the artifacts locally
  README.md
  cmd/pctl/install.go
  go.mod
  go.sum
  pkg/catalog/export_test.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/export_test.go
  pkg/profile/git_repo.go
  pkg/profile/helm.go
  pkg/profile/kustomize.go
  pkg/profile/profile.go
  pkg/profile/profile_suite_test.go
  pkg/repo/export_test.go
  pkg/repo/fakes/fake_http_client.go
  pkg/repo/git.go
  pkg/repo/git_suite_test.go
  pkg/repo/git_test.go
  pkg/writer/writer.go
  pkg/writer/writer_test.go
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: kind/improvement

#53 Fixing the integration test access
  .github/workflows/integration_test.yaml
  tests/integration/integration_test.go
Labels: bug, skip-release-notes

#56 Adding release process to PCTL
  .dockerignore
  .github/release-drafter.yml
  .github/workflows/release.yaml
  .github/workflows/release_drafter.yaml
  .goreleaser.yml
  Dockerfile
  README.md
  docs/release_notes/v0.0.1.md
Labels: kind/feature

#65 Fixed the create-pr test and introduced out folder to install
  cmd/pctl/install.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/git/git.go
  pkg/git/git_test.go
  tests/integration/integration_test.go
Labels: kind/bug

#66 Changing to repo location and outputting error on failed
  tests/integration/integration_test.go
Labels: kind/bug

#67 Using SSH to push
  .github/workflows/integration_test.yaml
  tests/integration/integration_test.go
Labels: kind/bug

#68 Fixing the path to the SSH key
  .github/workflows/integration_test.yaml
Labels: kind/bug

#64 Remove pctl get and update list to show catalog source instead of status
  README.md
  cmd/pctl/get.go
  cmd/pctl/list.go
  cmd/pctl/main.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/subscription/get.go
  pkg/subscription/get_test.go
  pkg/subscription/list.go
  pkg/subscription/list_test.go
  tests/integration/integration_test.go
Labels: kind/improvement

#78 organise artifact files in directories
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  tests/integration/integration_test.go
Labels: kind/improvement

#80 Install latest profile if no version is provided
  cmd/pctl/install.go
  pkg/catalog/install.go
  pkg/catalog/show.go
Labels: kind/feature

#82 Bump various deps
  go.mod
  go.sum
Labels: skip-release-notes

#83 update docs
  README.md
Labels: skip-release-notes

#69 Add ability to use branch path and url for developing profiles
  cmd/pctl/install.go
  cmd/pctl/list.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/git_repo.go
  pkg/profile/sanitise_branch.go
  pkg/profile/sanitise_branch_test.go
  pkg/subscription/list.go
  pkg/subscription/list_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#86 update flag help texts
  cmd/pctl/install.go
  cmd/pctl/list.go
  cmd/pctl/prepare.go
  cmd/pctl/search.go
  cmd/pctl/show.go
Labels: kind/improvement

#87 update docs
  README.md
  docs/assets/pctl_install.png
Labels: kind/improvement
