Repository weaveworks/pctl, pull requests merged in 2021-07, with the labels that each got.

#199 fix pctl install message
  cmd/pctl/install.go
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: kind/improvement

#200 bump deps
  Makefile
  go.mod
  go.sum
Labels: skip-release-notes

#202 add a newline to search output
  cmd/pctl/search.go
Labels: skip-release-notes

#207 Add docgen command to create md help docs
  cmd/pctl/docgen.go
  cmd/pctl/main.go
  tests/integration/integration_test.go
Labels: kind/feature

#208 Add notes for 0.0.4
  docs/release_notes/v0.0.4.md
Labels: skip-release-notes

#205 Add success message to install
  cmd/pctl/install.go
Labels: skip-release-notes

#214 Add pctl version flag
  .goreleaser.yml
  Makefile
  cmd/pctl/main.go
  go.mod
  go.sum
  pkg/version/generate/generate_suite_test.go
  pkg/version/generate/release_generate.go
  pkg/version/generate/release_generate_test.go
  pkg/version/parse.go
  pkg/version/parse_test.go
  pkg/version/release.go
  pkg/version/version.go
  pkg/version/version_suite_test.go
  pkg/version/version_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#221 Add support for upgrades
  .github/workflows/pr-tests.yaml
  cmd/pctl/install.go
  cmd/pctl/list.go
  cmd/pctl/main.go
  cmd/pctl/search.go
  cmd/pctl/show.go
  cmd/pctl/upgrade.go
  go.mod
  pkg/catalog/available_updates_test.go
  pkg/catalog/fakes/fake_catalog_manager.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/catalog/list.go
  pkg/catalog/list_test.go
  pkg/catalog/manager.go
  pkg/catalog/search.go
  pkg/catalog/search_test.go
  pkg/catalog/show.go
  pkg/catalog/show_test.go
  pkg/git/fakes/fake_git.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/upgrade/export_test.go
  pkg/upgrade/repo/fakes/fake_repo_manager.go
  pkg/upgrade/repo/manager.go
  pkg/upgrade/repo/manager_test.go
  pkg/upgrade/repo/repo_suite_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_suite_test.go
  pkg/upgrade/upgrade_test.go
  tests/integration/e2e_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#230 Fixing the root being passed in to the builder
  cmd/pctl/install.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  tests/integration/integration_install_test.go
Labels: skip-release-notes

#231 Present which files have conflicts to the user during upgrades
  pkg/git/fakes/fake_git.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/upgrade/repo/fakes/fake_repo_manager.go
  pkg/upgrade/repo/manager.go
  pkg/upgrade/repo/manager_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  tests/integration/e2e_test.go
Labels: kind/improvement

#229 store git repository resource in profile installation file
  cmd/pctl/install.go
  cmd/pctl/upgrade.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  tests/integration/e2e_test.go
  tests/integration/integration_install_test.go
Labels: kind/improvement

#232 Rename Profile package to install
  cmd/pctl/install.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/install/artifact/artifact.go
  pkg/install/builder/builder.go
  pkg/install/builder/builder_chart_test.go
  pkg/install/builder/builder_kustomize_test.go
  pkg/install/builder/builder_suite_test.go
  pkg/install/builder/fakes/builder_maker.go
  pkg/install/export_test.go
  pkg/install/fakes/fake_profile_installer.go
  pkg/install/installer.go
  pkg/install/installer_test.go
  pkg/install/make_artifacts.go
  pkg/install/make_artifacts_test.go
  pkg/install/profile_suite_test.go
  pkg/install/repo.go
  pkg/install/repo_test.go
  pkg/install/testdata/clone_cache/weaveworks-nginx-1/nginx/deployment/deployment.yaml
  pkg/install/testdata/clone_cache/weaveworks-nginx-1/profiles.yaml
  pkg/install/testdata/clone_cache/weaveworks-nginx-2/nginx2/deployment/deployment.yaml
  pkg/install/testdata/clone_cache/weaveworks-nginx-2/profiles.yaml
  pkg/install/testdata/dependson/weaveworks-nginx/profile.yaml
  pkg/install/testdata/dependson_missing/weaveworks-nginx/profile.yaml
  pkg/install/testdata/nested_with_self_link/weaveworks-nginx/profile.yaml
  pkg/install/testdata/simple_with_nested/bitnami-nginx/nginx/chart.yaml
  pkg/install/testdata/simple_with_nested/bitnami-nginx/profile.yaml
  pkg/install/testdata/simple_with_nested/weaveworks-nginx/nginx/deployment/deployment.yaml
  pkg/install/testdata/simple_with_nested/weaveworks-nginx/profile.yaml
  pkg/install/testdata/unknown_artifact_kind/weaveworks-nginx/profile.yaml
  pkg/profile/fakes/artifacts_maker.go
  pkg/upgrade/upgrade.go
Labels: skip-release-notes

#234 Rename `pctl install` to `pctl add`
  README.md
  cmd/pctl/add.go
  cmd/pctl/main.go
  tests/integration/e2e_test.go
  tests/integration/integration_add_test.go
  tests/integration/integration_docgen_test.go
Labels: kind/improvement

#235 Add support for depending on a nested profile
  cmd/pctl/add.go
  pkg/install/artifact/artifact.go
  pkg/install/artifact/artifact_chart_test.go
  pkg/install/artifact/artifact_kustomize_test.go
  pkg/install/artifact/artifact_nested_test.go
  pkg/install/artifact/artifact_suite_test.go
  pkg/install/artifact/fakes/fake_builder.go
  pkg/install/builder/builder.go
  pkg/install/builder/builder_chart_test.go
  pkg/install/builder/builder_kustomize_test.go
  pkg/install/builder/builder_suite_test.go
  pkg/install/builder/fakes/builder_maker.go
  pkg/install/export_test.go
  pkg/install/install_suite_test.go
  pkg/install/installer.go
  pkg/install/installer_test.go
  pkg/install/make_artifacts.go
  pkg/install/make_artifacts_test.go
  pkg/install/repo.go
  pkg/install/repo_test.go
  pkg/upgrade/upgrade.go
  tests/integration/integration_add_test.go
Labels: skip-release-notes

#238 add v0.2.0 release notes
  docs/release_notes/v0.2.0.md
Labels: skip-release-notes

#241 pctl version isn't correct
  README.md
  pkg/version/release.go
  tests/integration/integration_version_test.go
Labels: kind/bug, skip-release-notes
