Repository weaveworks/pctl, pull requests merged in 2021-06, with the labels that each got.

#96 Make the test repository configurable
  README.md
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#89 Rename files in pkg/repo
  pkg/repo/repo.go
  pkg/repo/repo_suite_test.go
  pkg/repo/repo_test.go
Labels: skip-release-notes

#85 Generate artifact files with 0644 perms
  pkg/catalog/install.go
  pkg/catalog/install_test.go
Labels: kind/improvement

#105 Fixing the username and secret for the release process and adding os …
  .github/workflows/release.yaml
  .goreleaser.yml
  pkg/runner/runner_suite_test.go
Labels: skip-release-notes

#107 Adding ability to get profile information from private repos
  .github/workflows/integration_test.yaml
  README.md
  cmd/pctl/install.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/git/fakes/fake_git.go
  pkg/git/git.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/profile.go
  pkg/repo/export_test.go
  pkg/repo/fakes/fake_http_client.go
  pkg/repo/repo.go
  pkg/repo/repo_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#111 default pr-branch to subName + random string
  cmd/pctl/install.go
Labels: kind/bug

#119 Clone repository local artifacts so they are available for the flux operator
  .golangci.yml
  README.md
  cmd/pctl/install.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/git/fakes/fake_git.go
  pkg/git/git.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/git_repo.go
  pkg/profile/helm.go
  pkg/profile/kustomize.go
  pkg/profile/profile.go
  pkg/repo/repo.go
  pkg/repo/repo_test.go
  tests/integration/catalog-source.yaml
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#129 fix pended integration test
  tests/integration/catalog-source.yaml
  tests/integration/integration_test.go
Labels: kind/bug

#135 fix bitnami version in integration tests
  tests/integration/integration_test.go
Labels: skip-release-notes

#130 fix pended unit test
  go.mod
  go.sum
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
Labels: kind/improvement

#136 Extracting the MakeArtifacts function into a provider
  cmd/pctl/install.go
  pkg/catalog/export_test.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/fakes/artifacts_maker.go
Labels: kind/improvement

#140 don't print table columns when no results found for list
  cmd/pctl/list.go
  pkg/catalog/list.go
Labels: kind/improvement

#137 use installation terminology instead of subscription
  README.md
  cmd/pctl/install.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/catalog/list.go
  pkg/catalog/list_test.go
  pkg/cluster/testdata/prepare.yaml
  pkg/git/git_test.go
  pkg/installation/installation_suite_test.go
  pkg/installation/list.go
  pkg/installation/list_test.go
  pkg/installation/manager.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/helm.go
  pkg/profile/kustomize.go
  pkg/profile/profile.go
  tests/integration/integration_test.go
Labels: kind/improvement

#142 Shifting the artifacts generation to the artifact maker
  cmd/pctl/install.go
  pkg/catalog/install.go
  pkg/catalog/install_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/fakes/artifacts_maker.go
  pkg/profile/testdata/simple_with_nested/bitnami-nginx/nginx/chart/Chart.yaml
  pkg/profile/testdata/simple_with_nested/bitnami-nginx/profiles.yaml
  pkg/profile/testdata/simple_with_nested/weaveworks-nginx/nginx/deployment/deployment.yaml
  pkg/profile/testdata/simple_with_nested/weaveworks-nginx/profiles.yaml
  tests/integration/integration_test.go
Labels: kind/improvement

#97 Adding working with latest version and check for version pin job
  .github/workflows/check_pinned_version.yaml
  Makefile
  README.md
Labels: kind/feature

#156 Fix integration tests
  tests/integration/catalog-source.yaml
  tests/integration/integration_test.go
Labels: skip-release-notes

#146 use flux create instead of flux bootstrap
  tests/integration/integration_test.go
Labels: skip-release-notes

#157 fix failing integration tests
  tests/integration/integration_test.go
Labels: skip-release-notes

#158 Run integration tests as part of PR flow
  .github/workflows/lint.yaml
  .github/workflows/pr-tests.yaml
  .github/workflows/unit_test.yaml
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: skip-release-notes

#144 Refactor using builders
  pkg/profile/artifact.go
  pkg/profile/artifact/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/builders.go
  pkg/profile/chart/builder.go
  pkg/profile/chart/builder_suite_test.go
  pkg/profile/chart/builder_test.go
  pkg/profile/export_test.go
  pkg/profile/fakes/builder_maker.go
  pkg/profile/helm.go
  pkg/profile/kustomize.go
  pkg/profile/kustomize/builder.go
  pkg/profile/kustomize/builder_suite_test.go
  pkg/profile/kustomize/builder_test.go
  pkg/profile/make_artifacts.go
  pkg/profile/make_artifacts_test.go
  pkg/profile/profile.go
  pkg/profile/sanitise_branch.go
  pkg/profile/sanitise_branch_test.go
  pkg/profile/testdata/simple_with_nested/bitnami-nginx/nginx/chart.yaml
  pkg/profile/testdata/simple_with_nested/bitnami-nginx/nginx/chart/Chart.yaml
  pkg/profile/testdata/simple_with_nested/bitnami-nginx/profiles.yaml
  pkg/profile/testdata/simple_with_nested/weaveworks-nginx/nginx/deployment/deployment.yaml
  pkg/profile/testdata/simple_with_nested/weaveworks-nginx/profiles.yaml
Labels: kind/improvement

#160 Fix support for local helm charts
  go.mod
  go.sum
  pkg/profile/artifact.go
  pkg/profile/artifact/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/chart/builder.go
  pkg/profile/chart/builder_test.go
  pkg/profile/make_artifacts_test.go
  tests/integration/integration_test.go
Labels: kind/bug

#161 pin go to 1.16
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#162 add some debug to ssh keys
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#145 Show all catalog entires
  README.md
  cmd/pctl/main.go
  cmd/pctl/search.go
  pkg/catalog/search.go
  pkg/catalog/search_test.go
  tests/integration/integration_test.go
Labels: kind/feature

#165 Revert "add some debug to ssh keys"
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#169 fix deploy-key setup
  .github/workflows/integration_test.yaml
  .github/workflows/ssh.config
  tests/integration/integration_suite_test.go
Labels: skip-release-notes

#174 fix deploy-key setupv2
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#175 fix workflow yaml
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#176 fix workflow yaml v2
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#177 fix workflow yaml v3
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#178 use $SSH consistently
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#179 use specific port in ssh config
  .github/workflows/integration_test.yaml
  .github/workflows/ssh.config
Labels: skip-release-notes

#180 Update integration_test.yaml
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#181 use GIT_SSH_COMMAND in integration tests
  .github/workflows/integration_test.yaml
  .github/workflows/ssh.config
  tests/integration/integration_suite_test.go
  tests/integration/integration_test.go
Labels: skip-release-notes

#182 keep current env set during integration test
  tests/integration/integration_test.go
Labels: skip-release-notes

#183 Sparse clone only per artifact
  pkg/git/git.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/export_test.go
  pkg/profile/make_artifacts.go
  pkg/profile/make_artifacts_test.go
  pkg/profile/profile.go
  pkg/profile/repo.go
  pkg/profile/repo_test.go
  pkg/profile/testdata/clone_cache/weaveworks-nginx-1/nginx/deployment/deployment.yaml
  pkg/profile/testdata/clone_cache/weaveworks-nginx-1/profiles.yaml
  pkg/profile/testdata/clone_cache/weaveworks-nginx-2/nginx2/deployment/deployment.yaml
  pkg/profile/testdata/clone_cache/weaveworks-nginx-2/profiles.yaml
  pkg/profile/testdata/nested_with_self_link/weaveworks-nginx/profile.yaml
  pkg/profile/testdata/simple_with_nested/bitnami-nginx/profile.yaml
  pkg/profile/testdata/simple_with_nested/bitnami-nginx/profiles.yaml
  pkg/profile/testdata/simple_with_nested/weaveworks-nginx/profile.yaml
  pkg/profile/testdata/unknown_artifact_kind/weaveworks-nginx/profile.yaml
  pkg/repo/repo_suite_test.go
  pkg/repo/repo_test.go
Labels: kind/improvement

#184 Testing out fixing using multiple deployment keys
  .github/workflows/integration_test.yaml
  scripts/ssh_command.sh
Labels: skip-release-notes

#185 Syntax error in yaml
  .github/workflows/integration_test.yaml
  scripts/ssh_command.sh
Labels: skip-release-notes

#186 Adding creating the folder
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#187 Fixing the chmod path
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#188 Fix the path of the script
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#189 Using $HOME
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#190 Shovelling everything into a single job
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#191 Removed using ${HOME}
  .github/workflows/integration_test.yaml
Labels: skip-release-notes

#192 Using a different folder than home folder
  .github/workflows/integration_test.yaml
  scripts/ssh_command.sh
Labels: skip-release-notes
